carapp/urls.py
from django.contrib import admin
from django.urls import path,include
from indexapp import views
from carapp import views

app_name='carapp'

urlpatterns = [
    path('admin/', admin.site.urls),
    path('car_page',views.car_page,name='car_page'),
    path('car',views.car,name='car'),
    path('car_del',views.car_del,name='car_del'),
    path('login_out',views.login_out,name='login_out'),
    path('updata',views.updata_car,name='updata'),



]

indentapp/urls.py
from django.contrib import admin
from django.urls import path,include
from indexapp import views
from indentapp import views

app_name='indentapp'

urlpatterns = [
    path('admin/', admin.site.urls),
    path('indent_page',views.indent_page,name='indent_page'),
    path('indent',views.indent,name='indent'),
    path('indent_out',views.indent_out,name='indent_out'),
    path('indent_ok',views.indent_ok,name='indent_ok'),
    path('address',views.address,name='address'),
    path('addr_page',views.addr_page,name='addr_page'),



]

indexapp/urls.py
from django.contrib import admin
from django.urls import path,include
from indexapp import views

app_name='indexapp'

urlpatterns = [
    path('admin/', admin.site.urls),
    path('indexapp/',views.addemp,name='indexapp'),
    path('add/',views.add,name='add'),
    path('index',views.index,name='index'),
    path('details',views.details,name='details'),
    path('booklist',views.booklist,name='booklist'),
    path('login_out/',views.login_out,name='login_out'),
    path('listlogin_out/',views.listlogin_out,name='listlogin_out'),
    path('details_out',views.details_out,name='details_out'),
    path('addemp',views.addemp,name='addemp'),


]

userapp/urls.py
from django.contrib import admin
from django.urls import path,include
from indexapp import views
from userapp import views

app_name='userapp'

urlpatterns = [
    path('admin/', admin.site.urls),
    path('register_page/',views.register_page,name='register_page'),
    path('register/',views.register,name='register'),
    path('getcaptcha/',views.getcaptcha,name='getcaptcha'),
    path('check_captcha/',views.check_captcha,name='check_captcha'),
    path('register_data/',views.register_data,name='register_data'),
    path('login_page',views.login_page,name='login_page'),
    path('login',views.login,name='login'),
    path('test',views.test,name='test'),
    path('mail',views.mail,name='mail'),
    path('req',views.req,name='req'),
    path('code',views.code,name='code'),
]

templates/addEmp.html
<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<html>
	<head>
		<title>add Emp</title>
		<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
		<link rel="stylesheet" type="text/css"
			href="/static/css/style.css" />
	</head>

	<body>
		<div id="wrap">
			<div id="top_content">
					<div id="header">
						<div id="rightheader">
							<p>
								2009/11/20
								<br />
							</p>
						</div>
						<div id="topheader">
							<h1 id="title">
								<a href="#">Main</a>
							</h1>
						</div>
						<div id="navigation">
						</div>
					</div>
				<div id="content">
					<p id="whereami">
					</p>
					<h1>
						add Emp info:
					</h1>
					<form action="{% url 'indexapp:add' %}" method="post" enctype="multipart/form-data">
                        {% csrf_token %}
						<table cellpadding="0" cellspacing="0" border="0"
							class="form_table">






							<tr>
								<td valign="middle" align="right">
									书籍分类:
								</td>
								<td valign="middle" align="left">
									<input type="text" class="inputgri" name="cate_id" />
								</td>
							</tr>

							<tr>
								<td valign="middle" align="right">
									书名:
								</td>
								<td valign="middle" align="left">
									<input type="text" class="inputgri" name="book_name" />
								</td>
							</tr>

                            <tr>
                                <td valign="middle" align="right">
									作者:
								</td>
                                <td>
                                    <input type="text" name="book_author">
                                </td>
                            </tr>
                            <tr>
                                <td valign="middle" align="right">
									出版社：
								</td>
                                <td>
                                    <input type="text" name="book_publish">
                                </td>
                            </tr><tr>
                                <td valign="middle" align="right">
									出版时间：
								</td>
                                <td>
                                    <input type="text" name="publish_time">
                                </td>
                            </tr>



                            <tr>
                                <td valign="middle" align="right">
                                    ISBN
								</td>
                                <td>
                                    <input type="text" name="book_isbn">
                                </td>
                            </tr>
                            <tr>
                                <td valign="middle" align="right">
                                字数
								</td>
                                <td>
                                    <input type="text" name="word_count">
                                </td>
                            </tr><tr>
                                <td valign="middle" align="right">
                                    页数
								</td>
                                <td>
                                    <input type="text" name="page_count">
                                </td>
                            </tr><tr>
                                <td valign="middle" align="right">
                                开本:16开
								</td>
                                <td>
                                    <input type="text" name="open_type">
                                </td>
                            </tr><tr>
                                <td valign="middle" align="right">
                                纯纸张
								</td>
                                <td>
                                    <input type="text" name="book_paper">
                                </td>
                            </tr><tr>
                                <td valign="middle" align="right">
                                包装：平装胶订
								</td>
                                <td>
                                    <input type="text" name="book_wrapper">
                                </td>
                            </tr><tr>
                                <td valign="middle" align="right">
                                分类：1.0
								</td>
                                <td>
                                    <input type="text" name="book_category">
                                </td>
                            </tr><tr>
                                <td valign="middle" align="right">
                                现价
								</td>
                                <td>
                                    <input type="text" name="book_price">
                                </td>
                            </tr>

                            <tr>
                                <td valign="middle" align="right">
                                原价
								</td>
                                <td>
                                    <input type="text" name="book_dprice">
                                </td>
                            </tr><tr>
                                <td valign="middle" align="right">
                                作者推荐书本
								</td>
                                <td>
                                    <input type="text" name="editor_recommendation">
                                </td>
                            </tr>







                            <tr>
                                <td valign="middle" align="right">
                                目录介绍
								</td>
                                <td>
                                    <input type="text" name="content_introduction">
                                </td>
                            </tr>


                            <tr>
                                <td valign="middle" align="right">
                            作者简介
								</td>
                                <td>
                                    <input type="text" name="author_introduction">
                                </td>
                            </tr><tr>
                                <td valign="middle" align="right">
                            随意三位数
								</td>
                                <td>
                                    <input type="text" name="media_review">
                                </td>
                            </tr>




                            <tr>
                                <td valign="middle" align="right">
                        图片路径
								</td>
                                <td>
                                    <input type="file" name="product_image_path">
                                </td>
                            </tr> <tr>
                                <td valign="middle" align="right">
                        出版时间
								</td>
                                <td>
                                    <input type="text" name="printing_time">
                                </td>
                            </tr><tr>
                                <td valign="middle" align="right">
                        一位数
								</td>
                                <td>
                                    <input type="text" name="impression">
                                </td>
                            </tr><tr>
                                <td valign="middle" align="right">
                        库存
								</td>
                                <td>
                                    <input type="text" name="stock">
                                </td>
                            </tr>
                            <tr>
                                <td valign="middle" align="right">
                        上架时间
								</td>
                                <td>
                                    <input type="text" name="shelves_date">
                                </td>
                            </tr><tr>
                                <td valign="middle" align="right">
                        打折数
								</td>
                                <td>
                                    <input type="text" name="customer_socre">
                                </td>
                            </tr>

                            <tr>
                                <td valign="middle" align="right">
                                销量
								</td>
                                <td>
                                    <input type="text" name="sales">
                                </td>
                            </tr>


						</table>
						<p>
							<input type="submit" class="button" value="Confirm" />
						</p>
					</form>
				</div>
			</div>
			<div id="footer">
				<div id="footer_bg">
					ABC@126.com
				</div>
			</div>
		</div>
	</body>
</html>

templates/mail.html
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">

<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<title>邮箱验证</title>
<link type="text/css" href=/static/css/register_150706.css rel="stylesheet">
<link href=/static/css/unite_header_1129.css rel="stylesheet" type="text/css">
<script src=/static/js/zhuce/pagetop_20121010.jstype="text/javascript"></script>
<script src="/static/js/jquery.1.4.2-min.js"></script>
{#    <script>#}
{#        function send_mail_code() {#}
            {#console.log("{{ username }}")#}
{#            username="{{ username }}"#}
{#            let uPattern=/^[1][3,4,5,7,8][0-9]{9}$/#}
{#            let uPattern2=/^([a-zA-Z0-9]+[_|\_|\.]?)*[a-zA-Z0-9]+@([a-zA-Z0-9]+[_|\_|\.]?)*[a-zA-Z0-9]+\.[a-zA-Z]{2,3}$/#}
{#            if (!uPattern2.test(username)){#}
{#                alert('对不起，您所注册的账号不是邮箱，无法进行验证！')#}
{#            }else{#}
{#                $.ajax({#}
{#                type:"GET",#}
{#                url:"{% url 'user:send_mail_code' %}",#}
{#                async: false,  //此处发送同步请求#}
{#                data:"mail="+"{{ username }}",#}
{#                success:function (rsp) {#}
{#                    if(rsp.status){#}
{#                        alert(rsp.msg)#}
{##}
{#                    }else {#}
{#                        alert(rsp.msg)#}
{#                    }#}
{#                }#}
{#                })#}
{#            }#}
{#        }#}
{##}
{##}
{#        function check_code() {#}
{#            $.ajax({#}
{#                type:"GET",#}
{#                url:"{% url 'user:check_mail_code' %}",#}
{#                async: false,  //此处发送同步请求#}
{#                data:"mail_code="+$("#nanmail").val(),#}
{#                success:function (rsp) {#}
{#                    if(rsp.status){#}
{#                        alert(rsp.msg)#}
{#                        location.href="{% url 'book_exhibition:index' %}"#}
{#                    }else {#}
{#                        alert(rsp.msg)#}
{#                    }#}
{#                }#}
{#                })#}
{#        }#}
{#        #}
{#        #}
{#        #}
{#    </script>#}
    
    
    
</head>

<body>
<div class="ddnewhead_wrap">
    <div class="ddnewhead_content ddnewhead_content2">
        <div class="ddnewhead_operate" id="__ddnav_menu">

        <p id="nickname">欢迎光临当当网，已有账号去<a name="ddnav_login" href="{% url 'userapp:login_page' %}" target="_self" class="login_link">登录</a><a name="ddnav_register" href="https://login.dangdang.com/Register.aspx" target="_self" class="login_link" style="display: none">免费注册</a></p>    </div>
              <div class="ddnewhead_logo"><a href="http://www.dangdang.com" title="返回首页" name="ddnav_logo"><img src=/static/images/zc_logo.jpg alt="百知网"></a></div>
      <div class="clear"></div>
    </div>
     <div class="ddnewcarthead_bottom"></div>
</div>
<form id="register_form" method="post" action="register.php" onsubmit="return false;">
        	<input style="display: none;" type="password">
            <div id="bd">
				<!--默认-->
				<div class="shadow_box">
					<div class="register_box">
						<div class="head">
							<span class="dd_more"><a href="{% url 'indexapp:index' %}" class="home">当当首页</a><a href="http://help.dangdang.com/details/page2">注册帮助</a></span>
							<a href="javascript:void(0);" class="head_a head_a1">新用户注册</a>
							<!--<a href="register_company.php?returnurl=http://book.dangdang.com/" class="head_a">企业用户注册</a>-->
						</div>
						<div class="body zccg">
							<p>注意查收验证码！</p>
                            <ul><li class="first">请输入验证码</li><li class="last"><input type="text" onblur="" id="nanmail" ></li></ul>
                            <ul style="display: none" id="nanfont2"><li><span id="nanfont"></span></li></ul>
                            <div class="zccg_btn">
                                <a href="javascript:void(0);" onclick="send_code();"><em></em><span id="nanemail">点击发送验证码</span></a>
                                <a href="javascript:void(0);" onclick="check()">立即验证</a>
                            </div>
						</div>
					</div>
				</div>
			</div>
    <script>
        function check() {
            $.ajax(
                {
                    type:'get',
                    url:"{% url 'userapp:code' %}",
                    data:"code="+$("#nanmail").val(),
                    success:function (msg) {
                        if(msg==="1"){
                            location.href="{% url 'userapp:register_data' %}"
                        }else{
                            alert('验证码不匹配')
                        }
                    }
                }
            )
        }

        function send_code() {
            $.ajax(
                {
                    type:'get',
                    url:"{% url 'userapp:req' %}",
                    async: false,  //此处发送同步请求
                    data:"mail="+"user",
                    success:function (msg) {
                        alert(msg)
                    }
                }
            )
        }
    </script>
    
    
    <img src="" alt="" width="20px" height="20px">
            <input id="btn_confirm" style="display: none" type="submit">
			<input name="hdn_username" id="hdn_username" type="hidden">
			<input name="hdn_mobile" id="hdn_mobile" type="hidden">
			<input name="hdn_password" id="hdn_password" type="hidden">
			<input name="action_post" id="action_post" value="register" type="hidden">
			<input name="returnurl" id="returnurl" value="http://book.dangdang.com/" type="hidden">
        </form>
<script src="/static/js/jquery-1.11.1.js"></script>
{#<script>#}
{#    var sign=0;#}
{#    function mailfn() {#}
{#              var code=$('#nanmail').val();#}
{#              if (code.length !== 16){#}
{#                  sign=0;#}
{#                  $('#nanfont2').css('display','block');#}
{#                  $('#nanfont').html('验证码不为16位!')#}
{#              }#}
{#              else {#}
{#                  $.ajax({#}
{#                      type: 'POST',#}
{#                      url: '/dangdang/emailajax/',#}
{#                      data: 'code='+code+'&username=15555555555'+'&csrfmiddlewaretoken=t0SdfUUC7o46XcMtac9nSv3eZ6KYk14165MXAtAmLcE1fGVeoWLVDhGPi6y7dYSC',#}
{#                      success: function (msg) {#}
{#                          if(msg == 1){#}
{#                              $('#nanfont2').css('display','block');#}
{#                              $('#nanfont').html('<img src=/static/images/right_3.jpg width="30px" height="30px">');#}
{#                              sign=1#}
{#                          }#}
{#                          else {#}
{#                              $('#nanfont2').css('display','block');#}
{#                              $('#nanfont').html('验证码验证不正确!');#}
{#                              sign=0#}
{#                          }#}
{##}
{#                      }#}
{#                  })#}
{#              }#}
{##}
{##}
{#    }#}
{#    function nansubmit() {#}
{#        if(sign == 1){#}
{#            location.href='/dangdang/emailok/?username=15555555555'#}
{#        }else {#}
{#            alert('验证码验证不正确!')#}
{#        }#}
{##}
{#    }#}
{#    function sendemailfn() {#}
{#        $.ajax({#}
{#            type:'POST',#}
{#            url:'/dangdang/sendemail/',#}
{#            data:'username=15555555555&csrfmiddlewaretoken=t0SdfUUC7o46XcMtac9nSv3eZ6KYk14165MXAtAmLcE1fGVeoWLVDhGPi6y7dYSC',#}
{#            success:function (msg) {#}
{#                if(msg == 1){#}
{#                    $('#nanemail').html('验证码发送成功!')#}
{#                }#}
{##}
{#            }#}
{#        })#}
{#    }#}

</script>
        <style type="text/css">
    .footer_nav_box{border-top: 1px solid #ebebeb;width:100%;_width:expression(this.scrollWidth < 960 ? "960px" : "auto");min-width: 960px;padding: 17px 0 50px;}
    .footer_nav_box a,.footer_nav_box{color: #8c8c8c;font-size: 12px;text-decoration: none;}
    .footer_nav_box a:hover{color: #f48570;text-decoration: underline;}
    .footer_nav_box .footer_nav{text-align: center;line-height: 20px;padding-bottom: 17px;padding-top: 25px;}
    .footer_nav_box .footer_nav span.sep{margin: 0 17px 0 19px;}
    .footer_nav_box .footer_copyright{line-height: 20px;text-align: center;width: 960px;margin: 0 auto;}
    .footer_nav_box .footer_copyright span.sep{margin:0 17px 0 19px;}
    .footer_nav_box .footer_icon{padding: 10px 0 0 340px;width: 640px;margin: 0 auto;height: 77px;}
    .footer_nav_box .validator,.footer_nav_box .knet{float:left;display:inline;padding:15px 5px 15px;width:135px;height:47px;}

    .footer_copyright {padding: 10px 0 0 0; margin: 0 auto;float: none; width: auto;text-align: center;color: #8c8c8c;}
    .footer_copyright span, .public_footer .footer_copyright a.footer_img { display: inline-block; float: none; }
    .footer_copyright a { padding: 0 4px; color: #8c8c8c;font-size: 12px;text-decoration: none;}
    .footer_copyright a:hover{color: #f48570;text-decoration: underline;}
    .footer_nav_box .footer_nav .footer_hot_search{display:inline-block;*display:inline;width:50px;position:relative}
    .footer_nav_box .footer_nav .pos_a_box{position:absolute;left:-251px;top:22px;background-color:#f48570;width:300px;border-radius:8px;text-align:center;height:14px;line-height:14px}
    .footer_nav_box .footer_nav .pos_a_box a,.footer_nav_box .footer_nav .pos_a_box a:hover,.footer_nav_box .footer_nav .pos_a_box span{padding:0 2px;color:#fff;text-decoration:none}
    .footer_nav_box .footer_nav .pos_a_box i{display:block;width:0;height:0;line-height:0;font-size:0;border-width:0 4px 4px;border-style:solid;border-color:#fff #fff #f48570 #fff;position:absolute;right:20px;top:-4px}
</style>
<div class="footer_nav_box">
    <div class="footer_nav"><a href="http://static.dangdang.com/topic/2227/176801.shtml" target="_blank" rel="nofollow">公司简介</a><span class="sep">|</span><a href="http://ir.dangdang.com/" target="_blank">Investor Relations</a><span class="sep">|</span><a href="http://zhaopin.dangdang.com" target="_blank">诚聘英才</a><span class="sep">|</span><a href="http://static.dangdang.com/topic/744/200778.shtml" target="_blank">手机当当</a><span class="sep">|</span><a href="http://union.dangdang.com/" target="_blank">网站联盟</a><span class="sep">|</span><a href="http://outlets.dangdang.com/merchants_open" target="_blank">当当招商</a><span class="sep">|</span><a href="http://misc.dangdang.com/groupbuy/Default.aspx" target="_blank" rel="nofollow">机构销售</a><span class="sep">|</span><a href="http://blog.dangdang.com/" target="_blank">官方Blog</a>
        <script>
            var setTo = null;
            function showghotsearch() {
                clearTimeout(setTo);
                document.getElementById("hot_search_content").style.display = "block";
            }
            function hidehotsearch() {
                setTo = setTimeout(function() {
                    document.getElementById("hot_search_content").style.display = "none";
                }, 100)
            }
        </script>
    </div>
    <div class="footer_copyright"><span>Copyright (C) 当当网 2004-2017, All Rights Reserved</span></div>
    <div class="footer_copyright"><span><a href="http://www.miibeian.gov.cn/" target="_blank" rel="nofollow">京ICP证041189号</a></span><span class="sep">|</span><span>出版物经营许可证 新出发京批字第直0673号</span><span class="sep">|</span><span>食品流通许可证：SP1101011010021855(1-1)</span><br><span>互联网药品信息服务资格证编号：(京)-非经营性-2012-0016</span><span class="sep">|</span><span>京公网安备110101000001号</span></div>
    <!-- 有三个icon的时候加footer_icon2 -->
    <div class="footer_icon footer_icon2" style="padding-left: 55px;">
        <div class="validator"><a href="http://www.hd315.gov.cn/beian/view.asp?bianhao=010202001051000098" target="_blank" class="footer_img"><img src=/static/images/validate.gif></a></div>
        <div class="knet"><!-- 可信网站LOGO安装开始 -->
            <script type="text/JavaScript">
                function CNNIC_change(eleId) {
                var str = document.getElementById(eleId).href;
                var str1 = str.substring(0, (str.length - 6));
                str1 += CNNIC_RndNum(6);
                document.getElementById(eleId).href = str1;
                }

                function CNNIC_RndNum(k) {
                var rnd = "";
                for (var i = 0; i < k; i++)
                rnd += Math.floor(Math.random() * 10);
                return rnd;
                }
            </script>
            <a href="https://ss.knet.cn/verifyseal.dll?sn=2010091900100002234&amp;pa=2940051" tabindex="-1" id="urlknet" target="_blank" rel="nofollow"><img alt="可信网站" name="CNNIC_seal" src=/static/images/knetSealLogo.png oncontextmenu="return false;" onclick="CNNIC_change('urlknet')" width="128" height="47" border="true"></a><!-- 可信网站LOGO安装结束 -->
        </div>
        <div class="validator"><a href="http://bj429.com.cn/" target="_blank" class="footer_img"><img src=/static/images/7d593c48-48f6-4fc9-85e0-7d6e10dfc2a2.hpvgUvc9></a></div>
        <div class="validator"><a id="_pingansec_bottomimagesmall_brand" href="http://si.trustutn.org/info?sn=302161014024825726885&amp;certType=1" target="_blank"><img src=/static/images/brand_128_47.png></a></div>
        <div class="clear"></div>
    </div>
</div>
</body>
</html>